### ISSUE TITLE
Progress bar throws error if there are less than 50 files to download

### ISSUE THREAD

**Issue by ChristinaKoss** [BCCN-Prog/dwd_2018#25]
To update the progress bar, the following calculation is made: i%int(len(filenames)/100)==0
If len(filenames)<50, this will result in a "division by zero" error.

This happens while trying to download the solar data (there are 45 files in that folder).

**Comment by imLew** [comment]
progressbar no longer uses modulo so this should be resolved
if you have a quick way to check please do so
