### ISSUE TITLE
process_data fails for some stations

### ISSUE THREAD

**Issue by bagibence** [BCCN-Prog/dwd_2018#33]
something went wrong processing station: 106

error: "local variable 'merged' referenced before assignment"

same for: 176, 321, 458, 508, 570, 594, 601, 604, 634, 743 and some others

**Comment by ChristinaKoss** [comment]
Should be solved now, see commits 39baa465f223dec568125d06938375c5b10b1f3f and bc5d60af141c890e3b2b8916a757c9733457e7bf
